// Baseline browser.
//
// Reads `baseline/failures.tsv` (generated by
// `scripts/corpus-baseline.sh` against Grysztar's fasm2 + fasmg
// corpora) and exposes a parsed list of failing files with their
// error spans. Entry paths look like:
//
//   C:\git\~tgrysztar\fasm2\include\macro\if.inc
//
// The `~tgrysztar\<repo>\<rest>` segment is the convention
// corpus-baseline.sh uses to tag entries. Mapping to a public raw URL
// is best-effort — not every local corpus file corresponds to an
// upstream tgrysztar/<repo> file with the same relative path, and
// branch/commit drift between the local snapshot and master may mean
// the error span shifts. When a baseline entry is loaded we fetch
// the remote equivalent on a best-effort basis; the row shows the
// original path so the user can manually reconcile if needed.

export async function loadFailuresTsv() {
  const url = new URL("../../baseline/failures.tsv", import.meta.url);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to load failures.tsv: ${response.status}`);
  }
  return response.text();
}

export function parseFailuresTsv(text) {
  const entries = [];
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const parts = line.split("\t");
    if (parts.length < 2) continue;

    const path = parts[0].trim();
    const metrics = parts.slice(1, parts.length - 1).join(" ").trim();
    const errorCell = parts[parts.length - 1].trim();

    const rangeMatch = errorCell.match(
      /\((ERROR|MISSING)\s+\[(\d+),\s*(\d+)\]\s*-\s*\[(\d+),\s*(\d+)\]\)/,
    );

    entries.push({
      path,
      metrics,
      errorKind: rangeMatch?.[1] ?? null,
      errorStart: rangeMatch
        ? { row: Number(rangeMatch[2]), column: Number(rangeMatch[3]) }
        : null,
      errorEnd: rangeMatch
        ? { row: Number(rangeMatch[4]), column: Number(rangeMatch[5]) }
        : null,
      remoteUrl: mapToRawUrl(path),
    });
  }
  return entries;
}

function mapToRawUrl(localPath) {
  const normalised = localPath.replace(/\\/g, "/");
  const match = normalised.match(/~tgrysztar\/([^/]+)\/(.+)$/);
  if (!match) return null;
  const [, repo, rest] = match;
  return `https://raw.githubusercontent.com/tgrysztar/${repo}/master/${rest}`;
}
